<a href="https://colab.research.google.com/github/sidh364/Export_Frontend_1/blob/main/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Basics**

In [ ]:
import numpy as np

In [ ]:
a = [1,3,5,4,2]
arr = np.array(a)
arr

array([1, 3, 5, 4, 2])

In [ ]:
b = arr*2
b

array([ 2,  6, 10,  8,  4])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr = np.logspace(1,3,3)
arr

array([  10.,  100., 1000.])

In [ ]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones(4,dtype = int)
arr

array([1, 1, 1, 1])

In [ ]:
arr = np.full(5,6)
arr

array([6, 6, 6, 6, 6])

In [ ]:
arr = np.random.rand(10)
arr

array([0.61443112, 0.80533733, 0.87848678, 0.51968551, 0.87619033,
       0.47012497, 0.28488795, 0.84663497, 0.13426706, 0.29286495])

In [ ]:
arr = np.random.randn(5)
arr

array([-1.25045094,  0.77991245, -0.5155903 , -0.52243   ,  0.63197006])

In [ ]:
arr = np.random.randint(5,100,5)
arr

array([52, 62, 55, 47, 77])

# **Numpy Data Types and type casting**

In [ ]:
arr = np.array([1,2,5,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst = ["atring",1,2.3,5,True]
arr = np.array(lst)
arr

array(['atring', '1', '2.3', '5', 'True'], dtype='<U32')

In [ ]:
arr = np.array([5,4,3,2,1,"dar"])
arr

array(['5', '4', '3', '2', '1', 'dar'], dtype='<U21')

In [ ]:
arr = np.array([1,2,3], dtype = np.float64)
new_arr = arr
new_arr

array([1., 2., 3.])

In [ ]:
arr = np.array([1,2,3])
new_arr = arr.astype(np.float64)
new_arr


array([1., 2., 3.])

# **Reshaping the array**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
rsp = arr.reshape(2,4)
rsp

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
rvl = rsp.ravel()
rvl

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
rvl[0] = 100
rvl

array([100,   2,   3,   4,   5,   6,   7,   8])

In [ ]:
rsp

array([[100,   2,   3,   4],
       [  5,   6,   7,   8]])

In [ ]:
flt = rvl.flatten()
flt

array([100,   2,   3,   4,   5,   6,   7,   8])

In [ ]:
flt[0] = 1
flt

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
rsp

array([[100,   2,   3,   4],
       [  5,   6,   7,   8]])

# **Arithmetic Operations On Array**

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [ ]:
a+b

array([5, 7, 9])

In [ ]:
a-b

array([-3, -3, -3])

In [ ]:
a/b

array([0.25, 0.4 , 0.5 ])

In [ ]:
a//b

array([0, 0, 0])

In [ ]:
a*b

array([ 4, 10, 18])

In [ ]:
(a+b)*2

array([10, 14, 18])

In [ ]:
arr = np.array([1,4,9,16])
np.sqrt(arr)

array([1., 2., 3., 4.])

In [ ]:
arr

array([ 1,  4,  9, 16])

In [ ]:
np.exp(arr)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [ ]:
arr = np.array([0,np.pi,np.pi/2])
np.sin(arr)

array([0.0000000e+00, 1.2246468e-16, 1.0000000e+00])

# Indexing and Slicing **bold text**

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[-1:-4]

array([], dtype=int64)

In [ ]:
a[-1:-4:-1]

array([5, 4, 3])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [ ]:
matrix[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
arr = np.array([[1,2],[3,4]])


In [ ]:
np.take(a, [0,3,4])

array([1, 4, 5])

In [ ]:
np.nonzero(a)

(array([0, 1, 2, 3, 4]),)

# **Iterate**

In [ ]:
for x in np.nditer(arr):
  print(x,end = " ")

1 2 3 4 

In [ ]:
for i, x in np.ndenumerate(arr):
  print(i,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
view = arr[1:4]
copy = arr[1:4].copy()


In [ ]:
view


array([2, 3, 4])

In [ ]:
copy

array([2, 3, 4])

In [ ]:
view[0] = 100
arr

array([  1, 100,   3,   4,   5])

In [ ]:
copy[1] = 200
arr

array([  1, 100,   3,   4,   5])

# **Transpose**

In [ ]:
arr = np.array([[[1,2],[3,4]]])

In [ ]:
arr.transpose()

array([[[1],
        [3]],

       [[2],
        [4]]])

In [ ]:
swap = np.swapaxes(arr, 0, 1)
swap

array([[[1, 2]],

       [[3, 4]]])

# **Concatination**

In [ ]:
arr = np.array([1,2,3,4,5,6])
a = arr[0:3]
b = arr[3:6]
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr3 = np.vstack((arr1,arr2))
arr3

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr3 = np.hstack((arr1,arr2))
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# **Repeating and Tiling**

In [ ]:
a = np.array([1,2,3])
rep = np.repeat(a,2)
rep

array([1, 1, 2, 2, 3, 3])

In [ ]:
til = np.tile(a,2)
til

array([1, 2, 3, 1, 2, 3])

# **Aggregate Functions**

In [ ]:
np.sum(arr)

np.int64(21)

In [ ]:
np.mean(arr)

np.float64(3.5)

In [ ]:
np.median(arr)

np.float64(3.5)

In [ ]:
np.max(arr)

np.int64(6)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.std(arr)

np.float64(1.707825127659933)

In [ ]:
np.var(arr)

np.float64(2.9166666666666665)

In [ ]:
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(matrix, axis = 0)

array([12, 15, 18])

# **Cumulatice operations**

In [ ]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21])

In [ ]:
np.cumprod(arr)

array([  1,   2,   6,  24, 120, 720])

# **Conditional based Choices**

In [ ]:
age = np.array([18,19,23,17,16,40,35,60,70,65])
np.where(age <18, "not_eligible", "eligible")


array(['eligible', 'eligible', 'eligible', 'not_eligible', 'not_eligible',
       'eligible', 'eligible', 'eligible', 'eligible', 'eligible'],
      dtype='<U12')

In [ ]:
np.argwhere(age<18)

array([[3],
       [4]])

In [ ]:
mask = np.logical_and(age>18, age<=60)
mask

array([False,  True,  True, False, False,  True,  True,  True, False,
       False])

In [ ]:
age[mask]

array([19, 23, 40, 35, 60])

# **Broadcasting**

In [ ]:
a = np.array([1,2,3])
b = np.array(5)
a+b

array([6, 7, 8])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([1,2])
a+b

array([[2, 4],
       [4, 6]])

# **Vectorization**

In [ ]:
def square(x):
  return x*x
vfunc = np.vectorize(square)

In [ ]:
a = [1, 2, 3, 4, 5, 6]
vfunc(a)

array([ 1,  4,  9, 16, 25, 36])

# **Missing Values**

In [ ]:
a = np.array([1,3,4,np.nan,6])

In [ ]:
a

array([ 1.,  3.,  4., nan,  6.])

In [ ]:
np.isnan(a)

array([False, False, False,  True, False])

In [ ]:
b = np.array([1,2,3,np.nan,np.inf,10])
np.isinf(a)

array([False, False, False, False, False])

In [ ]:
new_b = np.nan_to_num(b)
new_b = new_b.astype(int)
new_b

/tmp/ipython-input-1868338825.py:2: RuntimeWarning: invalid value encountered in cast
  new_b = new_b.astype(int)


array([                   1,                    2,                    3,
                          0, -9223372036854775808,                   10])